# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/telemetry/rpc_response_telemetry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.networking.requests import request_type_pb2 as pogoprotos_dot_networking_dot_requests_dot_request__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/telemetry/rpc_response_telemetry.proto',
  package='pogoprotos.data.telemetry',
  syntax='proto3',
  serialized_pb=_b('\n6pogoprotos/data/telemetry/rpc_response_telemetry.proto\x12\x19pogoprotos.data.telemetry\x1a\x31pogoprotos/networking/requests/request_type.proto\"\x8e\x02\n\x14RpcResponseTelemetry\x12\x17\n\x0fwindow_duration\x18\x01 \x01(\x02\x12Y\n\x10response_timings\x18\x02 \x03(\x0b\x32?.pogoprotos.data.telemetry.RpcResponseTelemetry.RpcResponseTime\x1a\x81\x01\n\x0fRpcResponseTime\x12;\n\x06rpc_id\x18\x01 \x01(\x0e\x32+.pogoprotos.networking.requests.RequestType\x12\x12\n\ncount_call\x18\x02 \x01(\x05\x12\x1d\n\x15\x61verage_response_time\x18\x03 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_networking_dot_requests_dot_request__type__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RPCRESPONSETELEMETRY_RPCRESPONSETIME = _descriptor.Descriptor(
  name='RpcResponseTime',
  full_name='pogoprotos.data.telemetry.RpcResponseTelemetry.RpcResponseTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpc_id', full_name='pogoprotos.data.telemetry.RpcResponseTelemetry.RpcResponseTime.rpc_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count_call', full_name='pogoprotos.data.telemetry.RpcResponseTelemetry.RpcResponseTime.count_call', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='average_response_time', full_name='pogoprotos.data.telemetry.RpcResponseTelemetry.RpcResponseTime.average_response_time', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=407,
)

_RPCRESPONSETELEMETRY = _descriptor.Descriptor(
  name='RpcResponseTelemetry',
  full_name='pogoprotos.data.telemetry.RpcResponseTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='window_duration', full_name='pogoprotos.data.telemetry.RpcResponseTelemetry.window_duration', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response_timings', full_name='pogoprotos.data.telemetry.RpcResponseTelemetry.response_timings', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RPCRESPONSETELEMETRY_RPCRESPONSETIME, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=407,
)

_RPCRESPONSETELEMETRY_RPCRESPONSETIME.fields_by_name['rpc_id'].enum_type = pogoprotos_dot_networking_dot_requests_dot_request__type__pb2._REQUESTTYPE
_RPCRESPONSETELEMETRY_RPCRESPONSETIME.containing_type = _RPCRESPONSETELEMETRY
_RPCRESPONSETELEMETRY.fields_by_name['response_timings'].message_type = _RPCRESPONSETELEMETRY_RPCRESPONSETIME
DESCRIPTOR.message_types_by_name['RpcResponseTelemetry'] = _RPCRESPONSETELEMETRY

RpcResponseTelemetry = _reflection.GeneratedProtocolMessageType('RpcResponseTelemetry', (_message.Message,), dict(

  RpcResponseTime = _reflection.GeneratedProtocolMessageType('RpcResponseTime', (_message.Message,), dict(
    DESCRIPTOR = _RPCRESPONSETELEMETRY_RPCRESPONSETIME,
    __module__ = 'pogoprotos.data.telemetry.rpc_response_telemetry_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.data.telemetry.RpcResponseTelemetry.RpcResponseTime)
    ))
  ,
  DESCRIPTOR = _RPCRESPONSETELEMETRY,
  __module__ = 'pogoprotos.data.telemetry.rpc_response_telemetry_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.telemetry.RpcResponseTelemetry)
  ))
_sym_db.RegisterMessage(RpcResponseTelemetry)
_sym_db.RegisterMessage(RpcResponseTelemetry.RpcResponseTime)


# @@protoc_insertion_point(module_scope)
