# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/friends/one_way_shared_friendship_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.gift import gift_box_details_pb2 as pogoprotos_dot_data_dot_gift_dot_gift__box__details__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/friends/one_way_shared_friendship_data.proto',
  package='pogoprotos.data.friends',
  syntax='proto3',
  serialized_pb=_b('\n<pogoprotos/data/friends/one_way_shared_friendship_data.proto\x12\x17pogoprotos.data.friends\x1a+pogoprotos/data/gift/gift_box_details.proto\"y\n\x1aOneWaySharedFriendshipData\x12=\n\x0fgiftbox_details\x18\x01 \x03(\x0b\x32$.pogoprotos.data.gift.GiftBoxDetails\x12\x1c\n\x14open_trade_expire_ms\x18\x02 \x01(\x03\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_gift_dot_gift__box__details__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ONEWAYSHAREDFRIENDSHIPDATA = _descriptor.Descriptor(
  name='OneWaySharedFriendshipData',
  full_name='pogoprotos.data.friends.OneWaySharedFriendshipData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='giftbox_details', full_name='pogoprotos.data.friends.OneWaySharedFriendshipData.giftbox_details', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open_trade_expire_ms', full_name='pogoprotos.data.friends.OneWaySharedFriendshipData.open_trade_expire_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=255,
)

_ONEWAYSHAREDFRIENDSHIPDATA.fields_by_name['giftbox_details'].message_type = pogoprotos_dot_data_dot_gift_dot_gift__box__details__pb2._GIFTBOXDETAILS
DESCRIPTOR.message_types_by_name['OneWaySharedFriendshipData'] = _ONEWAYSHAREDFRIENDSHIPDATA

OneWaySharedFriendshipData = _reflection.GeneratedProtocolMessageType('OneWaySharedFriendshipData', (_message.Message,), dict(
  DESCRIPTOR = _ONEWAYSHAREDFRIENDSHIPDATA,
  __module__ = 'pogoprotos.data.friends.one_way_shared_friendship_data_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.friends.OneWaySharedFriendshipData)
  ))
_sym_db.RegisterMessage(OneWaySharedFriendshipData)


# @@protoc_insertion_point(module_scope)
