# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/friends/player_friend_display.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data import pokemon_display_pb2 as pogoprotos_dot_data_dot_pokemon__display__pb2
from pogoprotos.enums import pokemon_id_pb2 as pogoprotos_dot_enums_dot_pokemon__id__pb2
from pogoprotos.enums import temporary_evolution_id_pb2 as pogoprotos_dot_enums_dot_temporary__evolution__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/friends/player_friend_display.proto',
  package='pogoprotos.data.friends',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n3pogoprotos/data/friends/player_friend_display.proto\x12\x17pogoprotos.data.friends\x1a%pogoprotos/data/pokemon_display.proto\x1a!pogoprotos/enums/pokemon_id.proto\x1a-pogoprotos/enums/temporary_evolution_id.proto\"\xa7\x04\n\x13PlayerFriendDisplay\x12.\n\x05\x62uddy\x18\x01 \x01(\x0b\x32\x1f.pogoprotos.data.PokemonDisplay\x12 \n\x18\x62uddy_display_pokemon_id\x18\x02 \x01(\x05\x12\x1e\n\x16\x62uddy_pokemon_nickname\x18\x03 \x01(\t\x12<\n\x13last_pokemon_caught\x18\x04 \x01(\x0b\x32\x1f.pogoprotos.data.PokemonDisplay\x12&\n\x1elast_pokemon_caught_display_id\x18\x05 \x01(\x05\x12%\n\x1dlast_pokemon_caught_timestamp\x18\x06 \x01(\x03\x12\x1b\n\x13\x62uddy_candy_awarded\x18\x07 \x01(\x05\x12V\n\x14\x61\x63tive_mega_evo_info\x18\x08 \x01(\x0b\x32\x38.pogoprotos.data.friends.PlayerFriendDisplay.MegaEvoInfo\x1a\x9b\x01\n\x0bMegaEvoInfo\x12/\n\npokedex_id\x18\x01 \x01(\x0e\x32\x1b.pogoprotos.enums.PokemonId\x12;\n\x0btemp_evo_id\x18\x02 \x01(\x0e\x32&.pogoprotos.enums.TemporaryEvolutionId\x12\x1e\n\x16\x65vo_expiration_time_ms\x18\x03 \x01(\x03\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_pokemon__display__pb2.DESCRIPTOR,pogoprotos_dot_enums_dot_pokemon__id__pb2.DESCRIPTOR,pogoprotos_dot_enums_dot_temporary__evolution__id__pb2.DESCRIPTOR,])




_PLAYERFRIENDDISPLAY_MEGAEVOINFO = _descriptor.Descriptor(
  name='MegaEvoInfo',
  full_name='pogoprotos.data.friends.PlayerFriendDisplay.MegaEvoInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokedex_id', full_name='pogoprotos.data.friends.PlayerFriendDisplay.MegaEvoInfo.pokedex_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp_evo_id', full_name='pogoprotos.data.friends.PlayerFriendDisplay.MegaEvoInfo.temp_evo_id', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evo_expiration_time_ms', full_name='pogoprotos.data.friends.PlayerFriendDisplay.MegaEvoInfo.evo_expiration_time_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=753,
)

_PLAYERFRIENDDISPLAY = _descriptor.Descriptor(
  name='PlayerFriendDisplay',
  full_name='pogoprotos.data.friends.PlayerFriendDisplay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buddy', full_name='pogoprotos.data.friends.PlayerFriendDisplay.buddy', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buddy_display_pokemon_id', full_name='pogoprotos.data.friends.PlayerFriendDisplay.buddy_display_pokemon_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buddy_pokemon_nickname', full_name='pogoprotos.data.friends.PlayerFriendDisplay.buddy_pokemon_nickname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_pokemon_caught', full_name='pogoprotos.data.friends.PlayerFriendDisplay.last_pokemon_caught', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_pokemon_caught_display_id', full_name='pogoprotos.data.friends.PlayerFriendDisplay.last_pokemon_caught_display_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_pokemon_caught_timestamp', full_name='pogoprotos.data.friends.PlayerFriendDisplay.last_pokemon_caught_timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buddy_candy_awarded', full_name='pogoprotos.data.friends.PlayerFriendDisplay.buddy_candy_awarded', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active_mega_evo_info', full_name='pogoprotos.data.friends.PlayerFriendDisplay.active_mega_evo_info', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PLAYERFRIENDDISPLAY_MEGAEVOINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=753,
)

_PLAYERFRIENDDISPLAY_MEGAEVOINFO.fields_by_name['pokedex_id'].enum_type = pogoprotos_dot_enums_dot_pokemon__id__pb2._POKEMONID
_PLAYERFRIENDDISPLAY_MEGAEVOINFO.fields_by_name['temp_evo_id'].enum_type = pogoprotos_dot_enums_dot_temporary__evolution__id__pb2._TEMPORARYEVOLUTIONID
_PLAYERFRIENDDISPLAY_MEGAEVOINFO.containing_type = _PLAYERFRIENDDISPLAY
_PLAYERFRIENDDISPLAY.fields_by_name['buddy'].message_type = pogoprotos_dot_data_dot_pokemon__display__pb2._POKEMONDISPLAY
_PLAYERFRIENDDISPLAY.fields_by_name['last_pokemon_caught'].message_type = pogoprotos_dot_data_dot_pokemon__display__pb2._POKEMONDISPLAY
_PLAYERFRIENDDISPLAY.fields_by_name['active_mega_evo_info'].message_type = _PLAYERFRIENDDISPLAY_MEGAEVOINFO
DESCRIPTOR.message_types_by_name['PlayerFriendDisplay'] = _PLAYERFRIENDDISPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerFriendDisplay = _reflection.GeneratedProtocolMessageType('PlayerFriendDisplay', (_message.Message,), dict(

  MegaEvoInfo = _reflection.GeneratedProtocolMessageType('MegaEvoInfo', (_message.Message,), dict(
    DESCRIPTOR = _PLAYERFRIENDDISPLAY_MEGAEVOINFO,
    __module__ = 'pogoprotos.data.friends.player_friend_display_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.data.friends.PlayerFriendDisplay.MegaEvoInfo)
    ))
  ,
  DESCRIPTOR = _PLAYERFRIENDDISPLAY,
  __module__ = 'pogoprotos.data.friends.player_friend_display_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.friends.PlayerFriendDisplay)
  ))
_sym_db.RegisterMessage(PlayerFriendDisplay)
_sym_db.RegisterMessage(PlayerFriendDisplay.MegaEvoInfo)


# @@protoc_insertion_point(module_scope)
