# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/ar_telemetry_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/master/ar_telemetry_settings.proto',
  package='pogoprotos.settings.master',
  syntax='proto3',
  serialized_pb=_b('\n6pogoprotos/settings/master/ar_telemetry_settings.proto\x12\x1apogoprotos.settings.master\"\xda\x01\n\x13\x41rTelemetrySettings\x12\x17\n\x0fmeasure_battery\x18\x01 \x01(\x08\x12$\n\x1c\x62\x61ttery_sampling_interval_ms\x18\x02 \x01(\x05\x12\x19\n\x11measure_processor\x18\x03 \x01(\x08\x12&\n\x1eprocessor_sampling_interval_ms\x18\x04 \x01(\x05\x12\x19\n\x11measure_framerate\x18\x05 \x01(\x08\x12&\n\x1e\x66ramerate_sampling_interval_ms\x18\x06 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ARTELEMETRYSETTINGS = _descriptor.Descriptor(
  name='ArTelemetrySettings',
  full_name='pogoprotos.settings.master.ArTelemetrySettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measure_battery', full_name='pogoprotos.settings.master.ArTelemetrySettings.measure_battery', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery_sampling_interval_ms', full_name='pogoprotos.settings.master.ArTelemetrySettings.battery_sampling_interval_ms', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='measure_processor', full_name='pogoprotos.settings.master.ArTelemetrySettings.measure_processor', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processor_sampling_interval_ms', full_name='pogoprotos.settings.master.ArTelemetrySettings.processor_sampling_interval_ms', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='measure_framerate', full_name='pogoprotos.settings.master.ArTelemetrySettings.measure_framerate', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='framerate_sampling_interval_ms', full_name='pogoprotos.settings.master.ArTelemetrySettings.framerate_sampling_interval_ms', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=305,
)

DESCRIPTOR.message_types_by_name['ArTelemetrySettings'] = _ARTELEMETRYSETTINGS

ArTelemetrySettings = _reflection.GeneratedProtocolMessageType('ArTelemetrySettings', (_message.Message,), dict(
  DESCRIPTOR = _ARTELEMETRYSETTINGS,
  __module__ = 'pogoprotos.settings.master.ar_telemetry_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.master.ArTelemetrySettings)
  ))
_sym_db.RegisterMessage(ArTelemetrySettings)


# @@protoc_insertion_point(module_scope)
