# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/pokemon_home_energy_costs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import pokemon_class_pb2 as pogoprotos_dot_enums_dot_pokemon__class__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/master/pokemon_home_energy_costs.proto',
  package='pogoprotos.settings.master',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n:pogoprotos/settings/master/pokemon_home_energy_costs.proto\x12\x1apogoprotos.settings.master\x1a$pogoprotos/enums/pokemon_class.proto\"\xae\x01\n\x16PokemonHomeEnergyCosts\x12\x35\n\rpokemon_class\x18\x01 \x01(\x0e\x32\x1e.pogoprotos.enums.PokemonClass\x12\x0c\n\x04\x62\x61se\x18\x02 \x01(\x05\x12\r\n\x05shiny\x18\x03 \x01(\x05\x12\x12\n\ncp0_to1000\x18\x04 \x01(\x05\x12\x15\n\rcp1001_to2000\x18\x05 \x01(\x05\x12\x15\n\rcp2001_to_inf\x18\x06 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_pokemon__class__pb2.DESCRIPTOR,])




_POKEMONHOMEENERGYCOSTS = _descriptor.Descriptor(
  name='PokemonHomeEnergyCosts',
  full_name='pogoprotos.settings.master.PokemonHomeEnergyCosts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokemon_class', full_name='pogoprotos.settings.master.PokemonHomeEnergyCosts.pokemon_class', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base', full_name='pogoprotos.settings.master.PokemonHomeEnergyCosts.base', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shiny', full_name='pogoprotos.settings.master.PokemonHomeEnergyCosts.shiny', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cp0_to1000', full_name='pogoprotos.settings.master.PokemonHomeEnergyCosts.cp0_to1000', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cp1001_to2000', full_name='pogoprotos.settings.master.PokemonHomeEnergyCosts.cp1001_to2000', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cp2001_to_inf', full_name='pogoprotos.settings.master.PokemonHomeEnergyCosts.cp2001_to_inf', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=303,
)

_POKEMONHOMEENERGYCOSTS.fields_by_name['pokemon_class'].enum_type = pogoprotos_dot_enums_dot_pokemon__class__pb2._POKEMONCLASS
DESCRIPTOR.message_types_by_name['PokemonHomeEnergyCosts'] = _POKEMONHOMEENERGYCOSTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PokemonHomeEnergyCosts = _reflection.GeneratedProtocolMessageType('PokemonHomeEnergyCosts', (_message.Message,), dict(
  DESCRIPTOR = _POKEMONHOMEENERGYCOSTS,
  __module__ = 'pogoprotos.settings.master.pokemon_home_energy_costs_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.master.PokemonHomeEnergyCosts)
  ))
_sym_db.RegisterMessage(PokemonHomeEnergyCosts)


# @@protoc_insertion_point(module_scope)
