# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/titan/requests/get_upload_url_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import player_submission_type_pb2 as pogoprotos_dot_enums_dot_player__submission__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/titan/requests/get_upload_url_message.proto',
  package='pogoprotos.networking.requests.titan.requests',
  syntax='proto3',
  serialized_pb=_b('\nJpogoprotos/networking/requests/titan/requests/get_upload_url_message.proto\x12-pogoprotos.networking.requests.titan.requests\x1a-pogoprotos/enums/player_submission_type.proto\"\xae\x01\n\x13GetUploadUrlMessage\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0egame_unique_id\x18\x02 \x01(\t\x12?\n\x0fsubmission_type\x18\x03 \x01(\x0e\x32&.pogoprotos.enums.PlayerSubmissionType\x12\x15\n\rsubmission_id\x18\x04 \x01(\t\x12\x16\n\x0eimage_contexts\x18\x05 \x03(\tb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_player__submission__type__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETUPLOADURLMESSAGE = _descriptor.Descriptor(
  name='GetUploadUrlMessage',
  full_name='pogoprotos.networking.requests.titan.requests.GetUploadUrlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='pogoprotos.networking.requests.titan.requests.GetUploadUrlMessage.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_unique_id', full_name='pogoprotos.networking.requests.titan.requests.GetUploadUrlMessage.game_unique_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='submission_type', full_name='pogoprotos.networking.requests.titan.requests.GetUploadUrlMessage.submission_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='submission_id', full_name='pogoprotos.networking.requests.titan.requests.GetUploadUrlMessage.submission_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_contexts', full_name='pogoprotos.networking.requests.titan.requests.GetUploadUrlMessage.image_contexts', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=347,
)

_GETUPLOADURLMESSAGE.fields_by_name['submission_type'].enum_type = pogoprotos_dot_enums_dot_player__submission__type__pb2._PLAYERSUBMISSIONTYPE
DESCRIPTOR.message_types_by_name['GetUploadUrlMessage'] = _GETUPLOADURLMESSAGE

GetUploadUrlMessage = _reflection.GeneratedProtocolMessageType('GetUploadUrlMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETUPLOADURLMESSAGE,
  __module__ = 'pogoprotos.networking.requests.titan.requests.get_upload_url_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.titan.requests.GetUploadUrlMessage)
  ))
_sym_db.RegisterMessage(GetUploadUrlMessage)


# @@protoc_insertion_point(module_scope)
