# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/game/gamepoi/requests/submit_poi_takedown_request_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/game/gamepoi/requests/submit_poi_takedown_request_message.proto',
  package='pogoprotos.networking.requests.game.gamepoi.requests',
  syntax='proto3',
  serialized_pb=_b('\n^pogoprotos/networking/requests/game/gamepoi/requests/submit_poi_takedown_request_message.proto\x12\x34pogoprotos.networking.requests.game.gamepoi.requests\"\xf8\x02\n\x1fSubmitPoiTakedownRequestMessage\x12\x0e\n\x06poi_id\x18\x01 \x01(\t\x12~\n\x0einvalid_reason\x18\x02 \x01(\x0e\x32\x66.pogoprotos.networking.requests.game.gamepoi.requests.SubmitPoiTakedownRequestMessage.PoiInvalidReason\"\xc4\x01\n\x10PoiInvalidReason\x12\x1e\n\x1aINVALID_REASON_UNSPECIFIED\x10\x00\x12\x18\n\x14NO_PEDESTRIAN_ACCESS\x10\x01\x12 \n\x1cOBSTRUCTS_EMERGENCY_SERVICES\x10\x02\x12 \n\x1cPRIVATE_RESIDENTIAL_PROPERTY\x10\x03\x12\n\n\x06SCHOOL\x10\x04\x12\x17\n\x13PERMANENTLY_REMOVED\x10\x05\x12\r\n\tDUPLICATE\x10\x06\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SUBMITPOITAKEDOWNREQUESTMESSAGE_POIINVALIDREASON = _descriptor.EnumDescriptor(
  name='PoiInvalidReason',
  full_name='pogoprotos.networking.requests.game.gamepoi.requests.SubmitPoiTakedownRequestMessage.PoiInvalidReason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_REASON_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_PEDESTRIAN_ACCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBSTRUCTS_EMERGENCY_SERVICES', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIVATE_RESIDENTIAL_PROPERTY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCHOOL', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERMANENTLY_REMOVED', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DUPLICATE', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=333,
  serialized_end=529,
)
_sym_db.RegisterEnumDescriptor(_SUBMITPOITAKEDOWNREQUESTMESSAGE_POIINVALIDREASON)


_SUBMITPOITAKEDOWNREQUESTMESSAGE = _descriptor.Descriptor(
  name='SubmitPoiTakedownRequestMessage',
  full_name='pogoprotos.networking.requests.game.gamepoi.requests.SubmitPoiTakedownRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poi_id', full_name='pogoprotos.networking.requests.game.gamepoi.requests.SubmitPoiTakedownRequestMessage.poi_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='invalid_reason', full_name='pogoprotos.networking.requests.game.gamepoi.requests.SubmitPoiTakedownRequestMessage.invalid_reason', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUBMITPOITAKEDOWNREQUESTMESSAGE_POIINVALIDREASON,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=529,
)

_SUBMITPOITAKEDOWNREQUESTMESSAGE.fields_by_name['invalid_reason'].enum_type = _SUBMITPOITAKEDOWNREQUESTMESSAGE_POIINVALIDREASON
_SUBMITPOITAKEDOWNREQUESTMESSAGE_POIINVALIDREASON.containing_type = _SUBMITPOITAKEDOWNREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['SubmitPoiTakedownRequestMessage'] = _SUBMITPOITAKEDOWNREQUESTMESSAGE

SubmitPoiTakedownRequestMessage = _reflection.GeneratedProtocolMessageType('SubmitPoiTakedownRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITPOITAKEDOWNREQUESTMESSAGE,
  __module__ = 'pogoprotos.networking.requests.game.gamepoi.requests.submit_poi_takedown_request_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.game.gamepoi.requests.SubmitPoiTakedownRequestMessage)
  ))
_sym_db.RegisterMessage(SubmitPoiTakedownRequestMessage)


# @@protoc_insertion_point(module_scope)
