# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/game/gameanticheat/requests/get_outstanding_warnings_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/game/gameanticheat/requests/get_outstanding_warnings_message.proto',
  package='pogoprotos.networking.requests.game.gameanticheat.requests',
  syntax='proto3',
  serialized_pb=_b('\napogoprotos/networking/requests/game/gameanticheat/requests/get_outstanding_warnings_message.proto\x12:pogoprotos.networking.requests.game.gameanticheat.requests\" \n\x1eGetOutstandingWarningsMessagesb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETOUTSTANDINGWARNINGSMESSAGES = _descriptor.Descriptor(
  name='GetOutstandingWarningsMessages',
  full_name='pogoprotos.networking.requests.game.gameanticheat.requests.GetOutstandingWarningsMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['GetOutstandingWarningsMessages'] = _GETOUTSTANDINGWARNINGSMESSAGES

GetOutstandingWarningsMessages = _reflection.GeneratedProtocolMessageType('GetOutstandingWarningsMessages', (_message.Message,), dict(
  DESCRIPTOR = _GETOUTSTANDINGWARNINGSMESSAGES,
  __module__ = 'pogoprotos.networking.requests.game.gameanticheat.requests.get_outstanding_warnings_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.game.gameanticheat.requests.GetOutstandingWarningsMessages)
  ))
_sym_db.RegisterMessage(GetOutstandingWarningsMessages)


# @@protoc_insertion_point(module_scope)
