# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/vasa/vasa_client_action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/vasa/vasa_client_action.proto',
  package='pogoprotos.networking.requests.vasa',
  syntax='proto3',
  serialized_pb=_b('\n<pogoprotos/networking/requests/vasa/vasa_client_action.proto\x12#pogoprotos.networking.requests.vasa\"S\n\x10VasaClientAction\"?\n\nActionEnum\x12\x1e\n\x1aINVALID_VASA_CLIENT_ACTION\x10\x00\x12\x11\n\x0c\x43OLLECT_ADID\x10\xc0>b\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_VASACLIENTACTION_ACTIONENUM = _descriptor.EnumDescriptor(
  name='ActionEnum',
  full_name='pogoprotos.networking.requests.vasa.VasaClientAction.ActionEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_VASA_CLIENT_ACTION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLLECT_ADID', index=1, number=8000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=121,
  serialized_end=184,
)
_sym_db.RegisterEnumDescriptor(_VASACLIENTACTION_ACTIONENUM)


_VASACLIENTACTION = _descriptor.Descriptor(
  name='VasaClientAction',
  full_name='pogoprotos.networking.requests.vasa.VasaClientAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VASACLIENTACTION_ACTIONENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=184,
)

_VASACLIENTACTION_ACTIONENUM.containing_type = _VASACLIENTACTION
DESCRIPTOR.message_types_by_name['VasaClientAction'] = _VASACLIENTACTION

VasaClientAction = _reflection.GeneratedProtocolMessageType('VasaClientAction', (_message.Message,), dict(
  DESCRIPTOR = _VASACLIENTACTION,
  __module__ = 'pogoprotos.networking.requests.vasa.vasa_client_action_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.vasa.VasaClientAction)
  ))
_sym_db.RegisterMessage(VasaClientAction)


# @@protoc_insertion_point(module_scope)
