# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/convert_candy_to_xl_candy_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import pokemon_family_id_pb2 as pogoprotos_dot_enums_dot_pokemon__family__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/convert_candy_to_xl_candy_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nOpogoprotos/networking/requests/messages/convert_candy_to_xl_candy_message.proto\x12\'pogoprotos.networking.requests.messages\x1a(pogoprotos/enums/pokemon_family_id.proto\"g\n\x1c\x43onvertCandyToXlCandyMessage\x12\x31\n\x06\x66\x61mily\x18\x01 \x01(\x0e\x32!.pogoprotos.enums.PokemonFamilyId\x12\x14\n\x0cnum_xl_candy\x18\x02 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_pokemon__family__id__pb2.DESCRIPTOR,])




_CONVERTCANDYTOXLCANDYMESSAGE = _descriptor.Descriptor(
  name='ConvertCandyToXlCandyMessage',
  full_name='pogoprotos.networking.requests.messages.ConvertCandyToXlCandyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='family', full_name='pogoprotos.networking.requests.messages.ConvertCandyToXlCandyMessage.family', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_xl_candy', full_name='pogoprotos.networking.requests.messages.ConvertCandyToXlCandyMessage.num_xl_candy', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=269,
)

_CONVERTCANDYTOXLCANDYMESSAGE.fields_by_name['family'].enum_type = pogoprotos_dot_enums_dot_pokemon__family__id__pb2._POKEMONFAMILYID
DESCRIPTOR.message_types_by_name['ConvertCandyToXlCandyMessage'] = _CONVERTCANDYTOXLCANDYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConvertCandyToXlCandyMessage = _reflection.GeneratedProtocolMessageType('ConvertCandyToXlCandyMessage', (_message.Message,), dict(
  DESCRIPTOR = _CONVERTCANDYTOXLCANDYMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.convert_candy_to_xl_candy_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.ConvertCandyToXlCandyMessage)
  ))
_sym_db.RegisterMessage(ConvertCandyToXlCandyMessage)


# @@protoc_insertion_point(module_scope)
