# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/create_pokemon_tag_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import pokemon_tag_color_pb2 as pogoprotos_dot_enums_dot_pokemon__tag__color__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/create_pokemon_tag_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nHpogoprotos/networking/requests/messages/create_pokemon_tag_message.proto\x12\'pogoprotos.networking.requests.messages\x1a(pogoprotos/enums/pokemon_tag_color.proto\"Y\n\x17\x43reatePokemonTagMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x30\n\x05\x63olor\x18\x02 \x01(\x0e\x32!.pogoprotos.enums.PokemonTagColorb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_pokemon__tag__color__pb2.DESCRIPTOR,])




_CREATEPOKEMONTAGMESSAGE = _descriptor.Descriptor(
  name='CreatePokemonTagMessage',
  full_name='pogoprotos.networking.requests.messages.CreatePokemonTagMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pogoprotos.networking.requests.messages.CreatePokemonTagMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='pogoprotos.networking.requests.messages.CreatePokemonTagMessage.color', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=248,
)

_CREATEPOKEMONTAGMESSAGE.fields_by_name['color'].enum_type = pogoprotos_dot_enums_dot_pokemon__tag__color__pb2._POKEMONTAGCOLOR
DESCRIPTOR.message_types_by_name['CreatePokemonTagMessage'] = _CREATEPOKEMONTAGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreatePokemonTagMessage = _reflection.GeneratedProtocolMessageType('CreatePokemonTagMessage', (_message.Message,), dict(
  DESCRIPTOR = _CREATEPOKEMONTAGMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.create_pokemon_tag_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.CreatePokemonTagMessage)
  ))
_sym_db.RegisterMessage(CreatePokemonTagMessage)


# @@protoc_insertion_point(module_scope)
