# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/delete_pokemon_tag_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/delete_pokemon_tag_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nHpogoprotos/networking/requests/messages/delete_pokemon_tag_message.proto\x12\'pogoprotos.networking.requests.messages\")\n\x17\x44\x65letePokemonTagMessage\x12\x0e\n\x06tag_id\x18\x01 \x01(\x04\x62\x06proto3')
)




_DELETEPOKEMONTAGMESSAGE = _descriptor.Descriptor(
  name='DeletePokemonTagMessage',
  full_name='pogoprotos.networking.requests.messages.DeletePokemonTagMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_id', full_name='pogoprotos.networking.requests.messages.DeletePokemonTagMessage.tag_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['DeletePokemonTagMessage'] = _DELETEPOKEMONTAGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeletePokemonTagMessage = _reflection.GeneratedProtocolMessageType('DeletePokemonTagMessage', (_message.Message,), dict(
  DESCRIPTOR = _DELETEPOKEMONTAGMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.delete_pokemon_tag_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.DeletePokemonTagMessage)
  ))
_sym_db.RegisterMessage(DeletePokemonTagMessage)


# @@protoc_insertion_point(module_scope)
