# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/get_photobomb_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/get_photobomb_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nCpogoprotos/networking/requests/messages/get_photobomb_message.proto\x12\'pogoprotos.networking.requests.messages\"\x15\n\x13GetPhotobombMessageb\x06proto3')
)




_GETPHOTOBOMBMESSAGE = _descriptor.Descriptor(
  name='GetPhotobombMessage',
  full_name='pogoprotos.networking.requests.messages.GetPhotobombMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['GetPhotobombMessage'] = _GETPHOTOBOMBMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPhotobombMessage = _reflection.GeneratedProtocolMessageType('GetPhotobombMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETPHOTOBOMBMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.get_photobomb_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.GetPhotobombMessage)
  ))
_sym_db.RegisterMessage(GetPhotobombMessage)


# @@protoc_insertion_point(module_scope)
