# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/open_sponsored_gift_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/open_sponsored_gift_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_pb=_b('\nIpogoprotos/networking/requests/messages/open_sponsored_gift_message.proto\x12\'pogoprotos.networking.requests.messages\"6\n\x18OpenSponsoredGiftMessage\x12\x1a\n\x12\x65ncrypted_ad_token\x18\x01 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OPENSPONSOREDGIFTMESSAGE = _descriptor.Descriptor(
  name='OpenSponsoredGiftMessage',
  full_name='pogoprotos.networking.requests.messages.OpenSponsoredGiftMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypted_ad_token', full_name='pogoprotos.networking.requests.messages.OpenSponsoredGiftMessage.encrypted_ad_token', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['OpenSponsoredGiftMessage'] = _OPENSPONSOREDGIFTMESSAGE

OpenSponsoredGiftMessage = _reflection.GeneratedProtocolMessageType('OpenSponsoredGiftMessage', (_message.Message,), dict(
  DESCRIPTOR = _OPENSPONSOREDGIFTMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.open_sponsored_gift_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.OpenSponsoredGiftMessage)
  ))
_sym_db.RegisterMessage(OpenSponsoredGiftMessage)


# @@protoc_insertion_point(module_scope)
