# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/set_pokemon_tags_for_pokemon_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/set_pokemon_tags_for_pokemon_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nRpogoprotos/networking/requests/messages/set_pokemon_tags_for_pokemon_message.proto\x12\'pogoprotos.networking.requests.messages\"\xda\x01\n\x1fSetPokemonTagsForPokemonMessage\x12h\n\x0btag_changes\x18\x01 \x03(\x0b\x32S.pogoprotos.networking.requests.messages.SetPokemonTagsForPokemonMessage.TagChanges\x1aM\n\nTagChanges\x12\x12\n\npokemon_id\x18\x01 \x01(\x03\x12\x13\n\x0btags_to_add\x18\x02 \x03(\x04\x12\x16\n\x0etags_to_remove\x18\x03 \x03(\x04\x62\x06proto3')
)




_SETPOKEMONTAGSFORPOKEMONMESSAGE_TAGCHANGES = _descriptor.Descriptor(
  name='TagChanges',
  full_name='pogoprotos.networking.requests.messages.SetPokemonTagsForPokemonMessage.TagChanges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokemon_id', full_name='pogoprotos.networking.requests.messages.SetPokemonTagsForPokemonMessage.TagChanges.pokemon_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags_to_add', full_name='pogoprotos.networking.requests.messages.SetPokemonTagsForPokemonMessage.TagChanges.tags_to_add', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags_to_remove', full_name='pogoprotos.networking.requests.messages.SetPokemonTagsForPokemonMessage.TagChanges.tags_to_remove', index=2,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=346,
)

_SETPOKEMONTAGSFORPOKEMONMESSAGE = _descriptor.Descriptor(
  name='SetPokemonTagsForPokemonMessage',
  full_name='pogoprotos.networking.requests.messages.SetPokemonTagsForPokemonMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_changes', full_name='pogoprotos.networking.requests.messages.SetPokemonTagsForPokemonMessage.tag_changes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SETPOKEMONTAGSFORPOKEMONMESSAGE_TAGCHANGES, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=346,
)

_SETPOKEMONTAGSFORPOKEMONMESSAGE_TAGCHANGES.containing_type = _SETPOKEMONTAGSFORPOKEMONMESSAGE
_SETPOKEMONTAGSFORPOKEMONMESSAGE.fields_by_name['tag_changes'].message_type = _SETPOKEMONTAGSFORPOKEMONMESSAGE_TAGCHANGES
DESCRIPTOR.message_types_by_name['SetPokemonTagsForPokemonMessage'] = _SETPOKEMONTAGSFORPOKEMONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetPokemonTagsForPokemonMessage = _reflection.GeneratedProtocolMessageType('SetPokemonTagsForPokemonMessage', (_message.Message,), dict(

  TagChanges = _reflection.GeneratedProtocolMessageType('TagChanges', (_message.Message,), dict(
    DESCRIPTOR = _SETPOKEMONTAGSFORPOKEMONMESSAGE_TAGCHANGES,
    __module__ = 'pogoprotos.networking.requests.messages.set_pokemon_tags_for_pokemon_message_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.SetPokemonTagsForPokemonMessage.TagChanges)
    ))
  ,
  DESCRIPTOR = _SETPOKEMONTAGSFORPOKEMONMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.set_pokemon_tags_for_pokemon_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.SetPokemonTagsForPokemonMessage)
  ))
_sym_db.RegisterMessage(SetPokemonTagsForPokemonMessage)
_sym_db.RegisterMessage(SetPokemonTagsForPokemonMessage.TagChanges)


# @@protoc_insertion_point(module_scope)
