# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/platform/requests/get_available_skus_and_balances_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/platform/requests/get_available_skus_and_balances_message.proto',
  package='pogoprotos.networking.requests.platform.requests',
  syntax='proto3',
  serialized_pb=_b('\n^pogoprotos/networking/requests/platform/requests/get_available_skus_and_balances_message.proto\x12\x30pogoprotos.networking.requests.platform.requests\"$\n\"GetAvailableSkusAndBalancesMessageb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETAVAILABLESKUSANDBALANCESMESSAGE = _descriptor.Descriptor(
  name='GetAvailableSkusAndBalancesMessage',
  full_name='pogoprotos.networking.requests.platform.requests.GetAvailableSkusAndBalancesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=184,
)

DESCRIPTOR.message_types_by_name['GetAvailableSkusAndBalancesMessage'] = _GETAVAILABLESKUSANDBALANCESMESSAGE

GetAvailableSkusAndBalancesMessage = _reflection.GeneratedProtocolMessageType('GetAvailableSkusAndBalancesMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETAVAILABLESKUSANDBALANCESMESSAGE,
  __module__ = 'pogoprotos.networking.requests.platform.requests.get_available_skus_and_balances_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.platform.requests.GetAvailableSkusAndBalancesMessage)
  ))
_sym_db.RegisterMessage(GetAvailableSkusAndBalancesMessage)


# @@protoc_insertion_point(module_scope)
