# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/account_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.settings import social_settings_pb2 as pogoprotos_dot_settings_dot_social__settings__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/account_settings.proto',
  package='pogoprotos.settings',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*pogoprotos/settings/account_settings.proto\x12\x13pogoprotos.settings\x1a)pogoprotos/settings/social_settings.proto\"\xaa\x02\n\x0f\x41\x63\x63ountSettings\x12#\n\x1bopt_out_social_graph_import\x18\x01 \x01(\x08\x12P\n\x15online_status_consent\x18\x02 \x01(\x0e\x32\x31.pogoprotos.settings.SocialSettings.ConsentStatus\x12S\n\x18last_played_date_consent\x18\x03 \x01(\x0e\x32\x31.pogoprotos.settings.SocialSettings.ConsentStatus\x12K\n\x10\x63odename_consent\x18\x04 \x01(\x0e\x32\x31.pogoprotos.settings.SocialSettings.ConsentStatusb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_settings_dot_social__settings__pb2.DESCRIPTOR,])




_ACCOUNTSETTINGS = _descriptor.Descriptor(
  name='AccountSettings',
  full_name='pogoprotos.settings.AccountSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opt_out_social_graph_import', full_name='pogoprotos.settings.AccountSettings.opt_out_social_graph_import', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='online_status_consent', full_name='pogoprotos.settings.AccountSettings.online_status_consent', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_played_date_consent', full_name='pogoprotos.settings.AccountSettings.last_played_date_consent', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codename_consent', full_name='pogoprotos.settings.AccountSettings.codename_consent', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=409,
)

_ACCOUNTSETTINGS.fields_by_name['online_status_consent'].enum_type = pogoprotos_dot_settings_dot_social__settings__pb2._SOCIALSETTINGS_CONSENTSTATUS
_ACCOUNTSETTINGS.fields_by_name['last_played_date_consent'].enum_type = pogoprotos_dot_settings_dot_social__settings__pb2._SOCIALSETTINGS_CONSENTSTATUS
_ACCOUNTSETTINGS.fields_by_name['codename_consent'].enum_type = pogoprotos_dot_settings_dot_social__settings__pb2._SOCIALSETTINGS_CONSENTSTATUS
DESCRIPTOR.message_types_by_name['AccountSettings'] = _ACCOUNTSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountSettings = _reflection.GeneratedProtocolMessageType('AccountSettings', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTSETTINGS,
  __module__ = 'pogoprotos.settings.account_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.AccountSettings)
  ))
_sym_db.RegisterMessage(AccountSettings)


# @@protoc_insertion_point(module_scope)
