# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/mega_evo_global_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/mega_evo_global_settings.proto',
  package='pogoprotos.settings',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n2pogoprotos/settings/mega_evo_global_settings.proto\x12\x13pogoprotos.settings\"O\n\x15MegaEvoGlobalSettings\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12%\n\x1d\x65nable_friends_list_mega_info\x18\x02 \x01(\x08\x62\x06proto3')
)




_MEGAEVOGLOBALSETTINGS = _descriptor.Descriptor(
  name='MegaEvoGlobalSettings',
  full_name='pogoprotos.settings.MegaEvoGlobalSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='pogoprotos.settings.MegaEvoGlobalSettings.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_friends_list_mega_info', full_name='pogoprotos.settings.MegaEvoGlobalSettings.enable_friends_list_mega_info', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['MegaEvoGlobalSettings'] = _MEGAEVOGLOBALSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MegaEvoGlobalSettings = _reflection.GeneratedProtocolMessageType('MegaEvoGlobalSettings', (_message.Message,), dict(
  DESCRIPTOR = _MEGAEVOGLOBALSETTINGS,
  __module__ = 'pogoprotos.settings.mega_evo_global_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.MegaEvoGlobalSettings)
  ))
_sym_db.RegisterMessage(MegaEvoGlobalSettings)


# @@protoc_insertion_point(module_scope)
