# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/planned_downtime_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/planned_downtime_settings.proto',
  package='pogoprotos.settings',
  syntax='proto3',
  serialized_pb=_b('\n3pogoprotos/settings/planned_downtime_settings.proto\x12\x13pogoprotos.settings\"e\n\x17PlannedDowntimeSettings\x12\x1d\n\x15\x64owntime_timestamp_ms\x18\x01 \x01(\x03\x12+\n#no_actions_window_sec_from_downtime\x18\x02 \x01(\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLANNEDDOWNTIMESETTINGS = _descriptor.Descriptor(
  name='PlannedDowntimeSettings',
  full_name='pogoprotos.settings.PlannedDowntimeSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='downtime_timestamp_ms', full_name='pogoprotos.settings.PlannedDowntimeSettings.downtime_timestamp_ms', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_actions_window_sec_from_downtime', full_name='pogoprotos.settings.PlannedDowntimeSettings.no_actions_window_sec_from_downtime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['PlannedDowntimeSettings'] = _PLANNEDDOWNTIMESETTINGS

PlannedDowntimeSettings = _reflection.GeneratedProtocolMessageType('PlannedDowntimeSettings', (_message.Message,), dict(
  DESCRIPTOR = _PLANNEDDOWNTIMESETTINGS,
  __module__ = 'pogoprotos.settings.planned_downtime_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.PlannedDowntimeSettings)
  ))
_sym_db.RegisterMessage(PlannedDowntimeSettings)


# @@protoc_insertion_point(module_scope)
