# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/social_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/social_settings.proto',
  package='pogoprotos.settings',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)pogoprotos/settings/social_settings.proto\x12\x13pogoprotos.settings\"\xb9\x01\n\x0eSocialSettings\"5\n\rConsentStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06OPT_IN\x10\x01\x12\x0b\n\x07OPT_OUT\x10\x02\"p\n\x0cTutorialType\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07PROFILE\x10\x01\x12\x12\n\x0e\x46RIEND_LIST_V2\x10\x02\x12\x1a\n\x16ONLINE_STATUS_OVERVIEW\x10\x03\x12\x18\n\x14ONLINE_STATUS_TOGGLE\x10\x04\x62\x06proto3')
)



_SOCIALSETTINGS_CONSENTSTATUS = _descriptor.EnumDescriptor(
  name='ConsentStatus',
  full_name='pogoprotos.settings.SocialSettings.ConsentStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPT_IN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPT_OUT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=85,
  serialized_end=138,
)
_sym_db.RegisterEnumDescriptor(_SOCIALSETTINGS_CONSENTSTATUS)

_SOCIALSETTINGS_TUTORIALTYPE = _descriptor.EnumDescriptor(
  name='TutorialType',
  full_name='pogoprotos.settings.SocialSettings.TutorialType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROFILE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRIEND_LIST_V2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONLINE_STATUS_OVERVIEW', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONLINE_STATUS_TOGGLE', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=140,
  serialized_end=252,
)
_sym_db.RegisterEnumDescriptor(_SOCIALSETTINGS_TUTORIALTYPE)


_SOCIALSETTINGS = _descriptor.Descriptor(
  name='SocialSettings',
  full_name='pogoprotos.settings.SocialSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SOCIALSETTINGS_CONSENTSTATUS,
    _SOCIALSETTINGS_TUTORIALTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=252,
)

_SOCIALSETTINGS_CONSENTSTATUS.containing_type = _SOCIALSETTINGS
_SOCIALSETTINGS_TUTORIALTYPE.containing_type = _SOCIALSETTINGS
DESCRIPTOR.message_types_by_name['SocialSettings'] = _SOCIALSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocialSettings = _reflection.GeneratedProtocolMessageType('SocialSettings', (_message.Message,), dict(
  DESCRIPTOR = _SOCIALSETTINGS,
  __module__ = 'pogoprotos.settings.social_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.SocialSettings)
  ))
_sym_db.RegisterMessage(SocialSettings)


# @@protoc_insertion_point(module_scope)
