# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/map/fort/incident_lookup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import enum_wrapper_pb2 as pogoprotos_dot_enums_dot_enum__wrapper__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/map/fort/incident_lookup.proto',
  package='pogoprotos.map.fort',
  syntax='proto3',
  serialized_pb=_b('\n)pogoprotos/map/fort/incident_lookup.proto\x12\x13pogoprotos.map.fort\x1a#pogoprotos/enums/enum_wrapper.proto\"\x9a\x01\n\x0eIncidentLookup\x12\x13\n\x0bincident_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66ort_id\x18\x02 \x01(\t\x12\x10\n\x08\x66ort_lat\x18\x03 \x01(\x01\x12\x10\n\x08\x66ort_lng\x18\x04 \x01(\x01\x12>\n\x07\x63ontext\x18\x05 \x01(\x0e\x32-.pogoprotos.enums.EnumWrapper.InvasionContextb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_enum__wrapper__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INCIDENTLOOKUP = _descriptor.Descriptor(
  name='IncidentLookup',
  full_name='pogoprotos.map.fort.IncidentLookup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='incident_id', full_name='pogoprotos.map.fort.IncidentLookup.incident_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fort_id', full_name='pogoprotos.map.fort.IncidentLookup.fort_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fort_lat', full_name='pogoprotos.map.fort.IncidentLookup.fort_lat', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fort_lng', full_name='pogoprotos.map.fort.IncidentLookup.fort_lng', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='pogoprotos.map.fort.IncidentLookup.context', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=258,
)

_INCIDENTLOOKUP.fields_by_name['context'].enum_type = pogoprotos_dot_enums_dot_enum__wrapper__pb2._ENUMWRAPPER_INVASIONCONTEXT
DESCRIPTOR.message_types_by_name['IncidentLookup'] = _INCIDENTLOOKUP

IncidentLookup = _reflection.GeneratedProtocolMessageType('IncidentLookup', (_message.Message,), dict(
  DESCRIPTOR = _INCIDENTLOOKUP,
  __module__ = 'pogoprotos.map.fort.incident_lookup_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.map.fort.IncidentLookup)
  ))
_sym_db.RegisterMessage(IncidentLookup)


# @@protoc_insertion_point(module_scope)
