# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/social/responses/list_friend_status_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.friends import friend_details_pb2 as pogoprotos_dot_data_dot_friends_dot_friend__details__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/social/responses/list_friend_status_response.proto',
  package='pogoprotos.networking.responses.social.responses',
  syntax='proto3',
  serialized_pb=_b('\nRpogoprotos/networking/responses/social/responses/list_friend_status_response.proto\x12\x30pogoprotos.networking.responses.social.responses\x1a,pogoprotos/data/friends/friend_details.proto\"\xec\x05\n\x18ListFriendStatusResponse\x12\x61\n\x06result\x18\x01 \x01(\x0e\x32Q.pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Result\x12\x36\n\x06\x66riend\x18\x02 \x03(\x0b\x32&.pogoprotos.data.friends.FriendDetails\x12s\n\x19\x66riend_details_debug_info\x18\x03 \x01(\x0b\x32P.pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug\x1a\xe7\x02\n\x05\x44\x65\x62ug\x12\x17\n\x0f\x66\x65tched_from_db\x18\x01 \x01(\x05\x12\x1b\n\x13\x66\x65tched_from_fanout\x18\x02 \x01(\x05\x12\"\n\x1a\x66\x65tched_from_player_mapper\x18\x03 \x01(\x05\x12!\n\x19\x66\x65tched_from_status_cache\x18\x04 \x01(\x05\x12\x17\n\x0f\x66\x61iled_to_fetch\x18\x05 \x01(\x05\x12l\n\x0b\x63\x61llee_list\x18\x06 \x03(\x0b\x32W.pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.Callee\x12*\n\"fetched_from_same_server_as_player\x18\x07 \x01(\x05\x1a.\n\x06\x43\x61llee\x12\x11\n\tcallee_id\x18\x01 \x03(\x05\x12\x11\n\tplayer_id\x18\x02 \x01(\t\"V\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x11\n\rERROR_UNKNOWN\x10\x02\x12!\n\x1d\x45XCEEDS_MAX_PLAYERS_PER_QUERY\x10\x03\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_friends_dot_friend__details__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_LISTFRIENDSTATUSRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXCEEDS_MAX_PLAYERS_PER_QUERY', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=845,
  serialized_end=931,
)
_sym_db.RegisterEnumDescriptor(_LISTFRIENDSTATUSRESPONSE_RESULT)


_LISTFRIENDSTATUSRESPONSE_DEBUG_CALLEE = _descriptor.Descriptor(
  name='Callee',
  full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.Callee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='callee_id', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.Callee.callee_id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.Callee.player_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=797,
  serialized_end=843,
)

_LISTFRIENDSTATUSRESPONSE_DEBUG = _descriptor.Descriptor(
  name='Debug',
  full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fetched_from_db', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.fetched_from_db', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fetched_from_fanout', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.fetched_from_fanout', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fetched_from_player_mapper', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.fetched_from_player_mapper', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fetched_from_status_cache', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.fetched_from_status_cache', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failed_to_fetch', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.failed_to_fetch', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='callee_list', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.callee_list', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fetched_from_same_server_as_player', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.fetched_from_same_server_as_player', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LISTFRIENDSTATUSRESPONSE_DEBUG_CALLEE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=843,
)

_LISTFRIENDSTATUSRESPONSE = _descriptor.Descriptor(
  name='ListFriendStatusResponse',
  full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friend', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.friend', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friend_details_debug_info', full_name='pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.friend_details_debug_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LISTFRIENDSTATUSRESPONSE_DEBUG, ],
  enum_types=[
    _LISTFRIENDSTATUSRESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=931,
)

_LISTFRIENDSTATUSRESPONSE_DEBUG_CALLEE.containing_type = _LISTFRIENDSTATUSRESPONSE_DEBUG
_LISTFRIENDSTATUSRESPONSE_DEBUG.fields_by_name['callee_list'].message_type = _LISTFRIENDSTATUSRESPONSE_DEBUG_CALLEE
_LISTFRIENDSTATUSRESPONSE_DEBUG.containing_type = _LISTFRIENDSTATUSRESPONSE
_LISTFRIENDSTATUSRESPONSE.fields_by_name['result'].enum_type = _LISTFRIENDSTATUSRESPONSE_RESULT
_LISTFRIENDSTATUSRESPONSE.fields_by_name['friend'].message_type = pogoprotos_dot_data_dot_friends_dot_friend__details__pb2._FRIENDDETAILS
_LISTFRIENDSTATUSRESPONSE.fields_by_name['friend_details_debug_info'].message_type = _LISTFRIENDSTATUSRESPONSE_DEBUG
_LISTFRIENDSTATUSRESPONSE_RESULT.containing_type = _LISTFRIENDSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['ListFriendStatusResponse'] = _LISTFRIENDSTATUSRESPONSE

ListFriendStatusResponse = _reflection.GeneratedProtocolMessageType('ListFriendStatusResponse', (_message.Message,), dict(

  Debug = _reflection.GeneratedProtocolMessageType('Debug', (_message.Message,), dict(

    Callee = _reflection.GeneratedProtocolMessageType('Callee', (_message.Message,), dict(
      DESCRIPTOR = _LISTFRIENDSTATUSRESPONSE_DEBUG_CALLEE,
      __module__ = 'pogoprotos.networking.responses.social.responses.list_friend_status_response_pb2'
      # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug.Callee)
      ))
    ,
    DESCRIPTOR = _LISTFRIENDSTATUSRESPONSE_DEBUG,
    __module__ = 'pogoprotos.networking.responses.social.responses.list_friend_status_response_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.social.responses.ListFriendStatusResponse.Debug)
    ))
  ,
  DESCRIPTOR = _LISTFRIENDSTATUSRESPONSE,
  __module__ = 'pogoprotos.networking.responses.social.responses.list_friend_status_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.social.responses.ListFriendStatusResponse)
  ))
_sym_db.RegisterMessage(ListFriendStatusResponse)
_sym_db.RegisterMessage(ListFriendStatusResponse.Debug)
_sym_db.RegisterMessage(ListFriendStatusResponse.Debug.Callee)


# @@protoc_insertion_point(module_scope)
