# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/game/gamegmtemplates/responses/download_game_master_templates_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.networking.responses import download_item_templates_response_pb2 as pogoprotos_dot_networking_dot_responses_dot_download__item__templates__response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/game/gamegmtemplates/responses/download_game_master_templates_response.proto',
  package='pogoprotos.networking.responses.game.gamegmtemplates.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nlpogoprotos/networking/responses/game/gamegmtemplates/responses/download_game_master_templates_response.proto\x12>pogoprotos.networking.responses.game.gamegmtemplates.responses\x1a\x46pogoprotos/networking/responses/download_item_templates_response.proto\"\xa2\x05\n#DownloadGameMasterTemplatesResponse\x12z\n\x06result\x18\x01 \x01(\x0e\x32j.pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.Result\x12\x8e\x01\n\x08template\x18\x02 \x03(\x0b\x32|.pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.ClientGameMasterTemplate\x12\x18\n\x10\x64\x65leted_template\x18\x03 \x03(\t\x12\x10\n\x08\x62\x61tch_id\x18\x04 \x01(\x04\x12\x13\n\x0bpage_offset\x18\x05 \x01(\x05\x12\x15\n\rexperiment_id\x18\x06 \x03(\x05\x1a\x96\x01\n\x18\x43lientGameMasterTemplate\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12\x65\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32W.pogoprotos.networking.responses.DownloadItemTemplatesResponse.GameMasterClientTemplate\"}\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0c\n\x08\x43OMPLETE\x10\x01\x12\x10\n\x0cMORE_RESULTS\x10\x02\x12\x15\n\x11\x42\x41TCH_ID_NOT_LIVE\x10\x03\x12\x1a\n\x16INVALID_BASIS_BATCH_ID\x10\x04\x12\x15\n\x11WRONG_EXPERIMENTS\x10\x05\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_networking_dot_responses_dot_download__item__templates__response__pb2.DESCRIPTOR,])



_DOWNLOADGAMEMASTERTEMPLATESRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MORE_RESULTS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATCH_ID_NOT_LIVE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_BASIS_BATCH_ID', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRONG_EXPERIMENTS', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=798,
  serialized_end=923,
)
_sym_db.RegisterEnumDescriptor(_DOWNLOADGAMEMASTERTEMPLATESRESPONSE_RESULT)


_DOWNLOADGAMEMASTERTEMPLATESRESPONSE_CLIENTGAMEMASTERTEMPLATE = _descriptor.Descriptor(
  name='ClientGameMasterTemplate',
  full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.ClientGameMasterTemplate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.ClientGameMasterTemplate.template_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.ClientGameMasterTemplate.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=646,
  serialized_end=796,
)

_DOWNLOADGAMEMASTERTEMPLATESRESPONSE = _descriptor.Descriptor(
  name='DownloadGameMasterTemplatesResponse',
  full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='template', full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.template', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deleted_template', full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.deleted_template', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.batch_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_offset', full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.page_offset', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experiment_id', full_name='pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.experiment_id', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DOWNLOADGAMEMASTERTEMPLATESRESPONSE_CLIENTGAMEMASTERTEMPLATE, ],
  enum_types=[
    _DOWNLOADGAMEMASTERTEMPLATESRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=923,
)

_DOWNLOADGAMEMASTERTEMPLATESRESPONSE_CLIENTGAMEMASTERTEMPLATE.fields_by_name['data'].message_type = pogoprotos_dot_networking_dot_responses_dot_download__item__templates__response__pb2._DOWNLOADITEMTEMPLATESRESPONSE_GAMEMASTERCLIENTTEMPLATE
_DOWNLOADGAMEMASTERTEMPLATESRESPONSE_CLIENTGAMEMASTERTEMPLATE.containing_type = _DOWNLOADGAMEMASTERTEMPLATESRESPONSE
_DOWNLOADGAMEMASTERTEMPLATESRESPONSE.fields_by_name['result'].enum_type = _DOWNLOADGAMEMASTERTEMPLATESRESPONSE_RESULT
_DOWNLOADGAMEMASTERTEMPLATESRESPONSE.fields_by_name['template'].message_type = _DOWNLOADGAMEMASTERTEMPLATESRESPONSE_CLIENTGAMEMASTERTEMPLATE
_DOWNLOADGAMEMASTERTEMPLATESRESPONSE_RESULT.containing_type = _DOWNLOADGAMEMASTERTEMPLATESRESPONSE
DESCRIPTOR.message_types_by_name['DownloadGameMasterTemplatesResponse'] = _DOWNLOADGAMEMASTERTEMPLATESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DownloadGameMasterTemplatesResponse = _reflection.GeneratedProtocolMessageType('DownloadGameMasterTemplatesResponse', (_message.Message,), dict(

  ClientGameMasterTemplate = _reflection.GeneratedProtocolMessageType('ClientGameMasterTemplate', (_message.Message,), dict(
    DESCRIPTOR = _DOWNLOADGAMEMASTERTEMPLATESRESPONSE_CLIENTGAMEMASTERTEMPLATE,
    __module__ = 'pogoprotos.networking.responses.game.gamegmtemplates.responses.download_game_master_templates_response_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse.ClientGameMasterTemplate)
    ))
  ,
  DESCRIPTOR = _DOWNLOADGAMEMASTERTEMPLATESRESPONSE,
  __module__ = 'pogoprotos.networking.responses.game.gamegmtemplates.responses.download_game_master_templates_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.game.gamegmtemplates.responses.DownloadGameMasterTemplatesResponse)
  ))
_sym_db.RegisterMessage(DownloadGameMasterTemplatesResponse)
_sym_db.RegisterMessage(DownloadGameMasterTemplatesResponse.ClientGameMasterTemplate)


# @@protoc_insertion_point(module_scope)
