# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/is_sku_available_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/is_sku_available_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n?pogoprotos/networking/responses/is_sku_available_response.proto\x12\x1fpogoprotos.networking.responses\"2\n\x16IsSkuAvailableResponse\x12\x18\n\x10is_sku_available\x18\x01 \x01(\x08\x62\x06proto3')
)




_ISSKUAVAILABLERESPONSE = _descriptor.Descriptor(
  name='IsSkuAvailableResponse',
  full_name='pogoprotos.networking.responses.IsSkuAvailableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_sku_available', full_name='pogoprotos.networking.responses.IsSkuAvailableResponse.is_sku_available', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['IsSkuAvailableResponse'] = _ISSKUAVAILABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IsSkuAvailableResponse = _reflection.GeneratedProtocolMessageType('IsSkuAvailableResponse', (_message.Message,), dict(
  DESCRIPTOR = _ISSKUAVAILABLERESPONSE,
  __module__ = 'pogoprotos.networking.responses.is_sku_available_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.IsSkuAvailableResponse)
  ))
_sym_db.RegisterMessage(IsSkuAvailableResponse)


# @@protoc_insertion_point(module_scope)
