# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/progress_quest_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.quests import client_quest_pb2 as pogoprotos_dot_data_dot_quests_dot_client__quest__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/progress_quest_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n=pogoprotos/networking/responses/progress_quest_response.proto\x12\x1fpogoprotos.networking.responses\x1a)pogoprotos/data/quests/client_quest.proto\"\xa6\x02\n\x15ProgressQuestResponse\x12M\n\x06status\x18\x01 \x01(\x0e\x32=.pogoprotos.networking.responses.ProgressQuestResponse.Status\x12\x32\n\x05quest\x18\x02 \x01(\x0b\x32#.pogoprotos.data.quests.ClientQuest\"\x89\x01\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x19\n\x15\x45RROR_QUEST_NOT_FOUND\x10\x02\x12/\n+ERROR_EXCEEDED_GEOTARGETED_SUBMISSION_LIMIT\x10\x03\x12\x1b\n\x17\x45RROR_VALIDATION_FAILED\x10\x04\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_quests_dot_client__quest__pb2.DESCRIPTOR,])



_PROGRESSQUESTRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pogoprotos.networking.responses.ProgressQuestResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_QUEST_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_EXCEEDED_GEOTARGETED_SUBMISSION_LIMIT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_VALIDATION_FAILED', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=299,
  serialized_end=436,
)
_sym_db.RegisterEnumDescriptor(_PROGRESSQUESTRESPONSE_STATUS)


_PROGRESSQUESTRESPONSE = _descriptor.Descriptor(
  name='ProgressQuestResponse',
  full_name='pogoprotos.networking.responses.ProgressQuestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pogoprotos.networking.responses.ProgressQuestResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quest', full_name='pogoprotos.networking.responses.ProgressQuestResponse.quest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROGRESSQUESTRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=436,
)

_PROGRESSQUESTRESPONSE.fields_by_name['status'].enum_type = _PROGRESSQUESTRESPONSE_STATUS
_PROGRESSQUESTRESPONSE.fields_by_name['quest'].message_type = pogoprotos_dot_data_dot_quests_dot_client__quest__pb2._CLIENTQUEST
_PROGRESSQUESTRESPONSE_STATUS.containing_type = _PROGRESSQUESTRESPONSE
DESCRIPTOR.message_types_by_name['ProgressQuestResponse'] = _PROGRESSQUESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProgressQuestResponse = _reflection.GeneratedProtocolMessageType('ProgressQuestResponse', (_message.Message,), dict(
  DESCRIPTOR = _PROGRESSQUESTRESPONSE,
  __module__ = 'pogoprotos.networking.responses.progress_quest_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.ProgressQuestResponse)
  ))
_sym_db.RegisterMessage(ProgressQuestResponse)


# @@protoc_insertion_point(module_scope)
