# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/unclassed/get_profile_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/unclassed/get_profile_response.proto',
  package='pogoprotos.data.unclassed',
  syntax='proto3',
  serialized_pb=_b('\n4pogoprotos/data/unclassed/get_profile_response.proto\x12\x19pogoprotos.data.unclassed\"\xf2\x04\n\x12GetProfileResponse\x12\x44\n\x06result\x18\x01 \x01(\x0e\x32\x34.pogoprotos.data.unclassed.GetProfileResponse.Result\x12U\n\x0fprofile_details\x18\x02 \x01(\x0b\x32<.pogoprotos.data.unclassed.GetProfileResponse.ProfileDetails\x12\x62\n\x16player_profile_details\x18\x03 \x03(\x0b\x32\x42.pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails\x1a\xcd\x01\n\x14PlayerProfileDetails\x12\x0f\n\x07\x61pp_key\x18\x01 \x01(\t\x12\x10\n\x08\x63odename\x18\x02 \x01(\t\x12\x0f\n\x07\x66\x61\x63tion\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x12\n\nexperience\x18\x05 \x01(\x03\x12\x1e\n\x16signed_up_timestamp_ms\x18\x06 \x01(\x03\x12 \n\x18last_played_timestamp_ms\x18\x07 \x01(\x03\x12\x1c\n\x14player_total_walk_km\x18\x08 \x01(\x01\x1a@\n\x0eProfileDetails\x12\x1c\n\x14profile_name_app_key\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\"I\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x11\n\rERROR_UNKNOWN\x10\x02\x12\x14\n\x10\x45RROR_NOT_FRIEND\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_GETPROFILERESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.data.unclassed.GetProfileResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NOT_FRIEND', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=637,
  serialized_end=710,
)
_sym_db.RegisterEnumDescriptor(_GETPROFILERESPONSE_RESULT)


_GETPROFILERESPONSE_PLAYERPROFILEDETAILS = _descriptor.Descriptor(
  name='PlayerProfileDetails',
  full_name='pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_key', full_name='pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails.app_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='codename', full_name='pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails.codename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='faction', full_name='pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails.faction', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experience', full_name='pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails.experience', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signed_up_timestamp_ms', full_name='pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails.signed_up_timestamp_ms', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_played_timestamp_ms', full_name='pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails.last_played_timestamp_ms', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_total_walk_km', full_name='pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails.player_total_walk_km', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=569,
)

_GETPROFILERESPONSE_PROFILEDETAILS = _descriptor.Descriptor(
  name='ProfileDetails',
  full_name='pogoprotos.data.unclassed.GetProfileResponse.ProfileDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_name_app_key', full_name='pogoprotos.data.unclassed.GetProfileResponse.ProfileDetails.profile_name_app_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='pogoprotos.data.unclassed.GetProfileResponse.ProfileDetails.nickname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=635,
)

_GETPROFILERESPONSE = _descriptor.Descriptor(
  name='GetProfileResponse',
  full_name='pogoprotos.data.unclassed.GetProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.data.unclassed.GetProfileResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profile_details', full_name='pogoprotos.data.unclassed.GetProfileResponse.profile_details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_profile_details', full_name='pogoprotos.data.unclassed.GetProfileResponse.player_profile_details', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GETPROFILERESPONSE_PLAYERPROFILEDETAILS, _GETPROFILERESPONSE_PROFILEDETAILS, ],
  enum_types=[
    _GETPROFILERESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=710,
)

_GETPROFILERESPONSE_PLAYERPROFILEDETAILS.containing_type = _GETPROFILERESPONSE
_GETPROFILERESPONSE_PROFILEDETAILS.containing_type = _GETPROFILERESPONSE
_GETPROFILERESPONSE.fields_by_name['result'].enum_type = _GETPROFILERESPONSE_RESULT
_GETPROFILERESPONSE.fields_by_name['profile_details'].message_type = _GETPROFILERESPONSE_PROFILEDETAILS
_GETPROFILERESPONSE.fields_by_name['player_profile_details'].message_type = _GETPROFILERESPONSE_PLAYERPROFILEDETAILS
_GETPROFILERESPONSE_RESULT.containing_type = _GETPROFILERESPONSE
DESCRIPTOR.message_types_by_name['GetProfileResponse'] = _GETPROFILERESPONSE

GetProfileResponse = _reflection.GeneratedProtocolMessageType('GetProfileResponse', (_message.Message,), dict(

  PlayerProfileDetails = _reflection.GeneratedProtocolMessageType('PlayerProfileDetails', (_message.Message,), dict(
    DESCRIPTOR = _GETPROFILERESPONSE_PLAYERPROFILEDETAILS,
    __module__ = 'pogoprotos.data.unclassed.get_profile_response_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.data.unclassed.GetProfileResponse.PlayerProfileDetails)
    ))
  ,

  ProfileDetails = _reflection.GeneratedProtocolMessageType('ProfileDetails', (_message.Message,), dict(
    DESCRIPTOR = _GETPROFILERESPONSE_PROFILEDETAILS,
    __module__ = 'pogoprotos.data.unclassed.get_profile_response_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.data.unclassed.GetProfileResponse.ProfileDetails)
    ))
  ,
  DESCRIPTOR = _GETPROFILERESPONSE,
  __module__ = 'pogoprotos.data.unclassed.get_profile_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.unclassed.GetProfileResponse)
  ))
_sym_db.RegisterMessage(GetProfileResponse)
_sym_db.RegisterMessage(GetProfileResponse.PlayerProfileDetails)
_sym_db.RegisterMessage(GetProfileResponse.ProfileDetails)


# @@protoc_insertion_point(module_scope)
