# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/unclassed/update_profile_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/unclassed/update_profile_response.proto',
  package='pogoprotos.data.unclassed',
  syntax='proto3',
  serialized_pb=_b('\n7pogoprotos/data/unclassed/update_profile_response.proto\x12\x19pogoprotos.data.unclassed\"\x95\x01\n\x15UpdateProfileResponse\x12G\n\x06result\x18\x01 \x01(\x0e\x32\x37.pogoprotos.data.unclassed.UpdateProfileResponse.Result\"3\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x11\n\rERROR_UNKNOWN\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_UPDATEPROFILERESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.data.unclassed.UpdateProfileResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=185,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_UPDATEPROFILERESPONSE_RESULT)


_UPDATEPROFILERESPONSE = _descriptor.Descriptor(
  name='UpdateProfileResponse',
  full_name='pogoprotos.data.unclassed.UpdateProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.data.unclassed.UpdateProfileResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UPDATEPROFILERESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=236,
)

_UPDATEPROFILERESPONSE.fields_by_name['result'].enum_type = _UPDATEPROFILERESPONSE_RESULT
_UPDATEPROFILERESPONSE_RESULT.containing_type = _UPDATEPROFILERESPONSE
DESCRIPTOR.message_types_by_name['UpdateProfileResponse'] = _UPDATEPROFILERESPONSE

UpdateProfileResponse = _reflection.GeneratedProtocolMessageType('UpdateProfileResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEPROFILERESPONSE,
  __module__ = 'pogoprotos.data.unclassed.update_profile_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.unclassed.UpdateProfileResponse)
  ))
_sym_db.RegisterMessage(UpdateProfileResponse)


# @@protoc_insertion_point(module_scope)
