# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/sticker/sticker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/sticker/sticker.proto',
  package='pogoprotos.data.sticker',
  syntax='proto3',
  serialized_pb=_b('\n%pogoprotos/data/sticker/sticker.proto\x12\x17pogoprotos.data.sticker\":\n\x07Sticker\x12\x12\n\nsticker_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0c\n\x04used\x18\x03 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STICKER = _descriptor.Descriptor(
  name='Sticker',
  full_name='pogoprotos.data.sticker.Sticker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sticker_id', full_name='pogoprotos.data.sticker.Sticker.sticker_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='pogoprotos.data.sticker.Sticker.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='used', full_name='pogoprotos.data.sticker.Sticker.used', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['Sticker'] = _STICKER

Sticker = _reflection.GeneratedProtocolMessageType('Sticker', (_message.Message,), dict(
  DESCRIPTOR = _STICKER,
  __module__ = 'pogoprotos.data.sticker.sticker_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.sticker.Sticker)
  ))
_sym_db.RegisterMessage(Sticker)


# @@protoc_insertion_point(module_scope)
