# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/sticker/sticker_metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import pokemon_id_pb2 as pogoprotos_dot_enums_dot_pokemon__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/sticker/sticker_metadata.proto',
  package='pogoprotos.data.sticker',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.pogoprotos/data/sticker/sticker_metadata.proto\x12\x17pogoprotos.data.sticker\x1a!pogoprotos/enums/pokemon_id.proto\"~\n\x0fStickerMetadata\x12\x12\n\nsticker_id\x18\x01 \x01(\t\x12\x13\n\x0bsticker_url\x18\x02 \x01(\t\x12\x11\n\tmax_count\x18\x03 \x01(\x05\x12/\n\npokemon_id\x18\x04 \x01(\x0e\x32\x1b.pogoprotos.enums.PokemonIdb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_pokemon__id__pb2.DESCRIPTOR,])




_STICKERMETADATA = _descriptor.Descriptor(
  name='StickerMetadata',
  full_name='pogoprotos.data.sticker.StickerMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sticker_id', full_name='pogoprotos.data.sticker.StickerMetadata.sticker_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sticker_url', full_name='pogoprotos.data.sticker.StickerMetadata.sticker_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_count', full_name='pogoprotos.data.sticker.StickerMetadata.max_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pokemon_id', full_name='pogoprotos.data.sticker.StickerMetadata.pokemon_id', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=236,
)

_STICKERMETADATA.fields_by_name['pokemon_id'].enum_type = pogoprotos_dot_enums_dot_pokemon__id__pb2._POKEMONID
DESCRIPTOR.message_types_by_name['StickerMetadata'] = _STICKERMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StickerMetadata = _reflection.GeneratedProtocolMessageType('StickerMetadata', (_message.Message,), dict(
  DESCRIPTOR = _STICKERMETADATA,
  __module__ = 'pogoprotos.data.sticker.sticker_metadata_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.sticker.StickerMetadata)
  ))
_sym_db.RegisterMessage(StickerMetadata)


# @@protoc_insertion_point(module_scope)
