# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/titan/responses/player_submission_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/titan/responses/player_submission_response.proto',
  package='pogoprotos.networking.responses.titan',
  syntax='proto3',
  serialized_pb=_b('\nPpogoprotos/networking/responses/titan/responses/player_submission_response.proto\x12%pogoprotos.networking.responses.titan\"\xe4\x02\n\x18PlayerSubmissionResponse\x12V\n\x06status\x18\x01 \x01(\x0e\x32\x46.pogoprotos.networking.responses.titan.PlayerSubmissionResponse.Status\x12\x15\n\rsubmission_id\x18\x02 \x01(\t\x12\x10\n\x08messages\x18\x03 \x03(\t\"\xc6\x01\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x1f\n\x1bTOO_MANY_RECENT_SUBMISSIONS\x10\x03\x12\t\n\x05MINOR\x10\x04\x12\x11\n\rNOT_AVAILABLE\x10\x05\x12\x11\n\rINVALID_INPUT\x10\x06\x12\x11\n\rMISSING_IMAGE\x10\x07\x12\x1e\n\x1a\x44ISTANCE_VALIDATION_FAILED\x10\x08\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PLAYERSUBMISSIONRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pogoprotos.networking.responses.titan.PlayerSubmissionResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOO_MANY_RECENT_SUBMISSIONS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MINOR', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_AVAILABLE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_INPUT', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSING_IMAGE', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTANCE_VALIDATION_FAILED', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=282,
  serialized_end=480,
)
_sym_db.RegisterEnumDescriptor(_PLAYERSUBMISSIONRESPONSE_STATUS)


_PLAYERSUBMISSIONRESPONSE = _descriptor.Descriptor(
  name='PlayerSubmissionResponse',
  full_name='pogoprotos.networking.responses.titan.PlayerSubmissionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pogoprotos.networking.responses.titan.PlayerSubmissionResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='submission_id', full_name='pogoprotos.networking.responses.titan.PlayerSubmissionResponse.submission_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messages', full_name='pogoprotos.networking.responses.titan.PlayerSubmissionResponse.messages', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLAYERSUBMISSIONRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=480,
)

_PLAYERSUBMISSIONRESPONSE.fields_by_name['status'].enum_type = _PLAYERSUBMISSIONRESPONSE_STATUS
_PLAYERSUBMISSIONRESPONSE_STATUS.containing_type = _PLAYERSUBMISSIONRESPONSE
DESCRIPTOR.message_types_by_name['PlayerSubmissionResponse'] = _PLAYERSUBMISSIONRESPONSE

PlayerSubmissionResponse = _reflection.GeneratedProtocolMessageType('PlayerSubmissionResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERSUBMISSIONRESPONSE,
  __module__ = 'pogoprotos.networking.responses.titan.responses.player_submission_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.titan.PlayerSubmissionResponse)
  ))
_sym_db.RegisterMessage(PlayerSubmissionResponse)


# @@protoc_insertion_point(module_scope)
