# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/quests/quest_dialog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/quests/quest_dialog.proto',
  package='pogoprotos.data.quests',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)pogoprotos/data/quests/quest_dialog.proto\x12\x16pogoprotos.data.quests\"\xf0\x05\n\x0bQuestDialog\x12\x0c\n\x04text\x18\x01 \x01(\t\x12K\n\nexpression\x18\x02 \x01(\x0e\x32\x37.pogoprotos.data.quests.QuestDialog.CharacterExpression\x12\x11\n\timage_uri\x18\x03 \x01(\t\x12@\n\tcharacter\x18\x04 \x01(\x0e\x32-.pogoprotos.data.quests.QuestDialog.Character\x12\x18\n\x10\x63haracter_offset\x18\x05 \x03(\x02\x12\x1d\n\x15text_background_color\x18\x06 \x01(\t\x12\x16\n\x0e\x63haracter_tint\x18\x07 \x01(\t\"\xbd\x02\n\x13\x43haracterExpression\x12\x14\n\x10\x45XPRESSION_UNSET\x10\x00\x12\t\n\x05HAPPY\x10\x01\x12\x0f\n\x0bSYMPATHETIC\x10\x02\x12\r\n\tENERGETIC\x10\x03\x12\t\n\x05PUSHY\x10\x04\x12\r\n\tIMPATIENT\x10\x05\x12\x0e\n\nADMIRATION\x10\x06\x12\x07\n\x03SAD\x10\x07\x12\x08\n\x04IDLE\x10\x08\x12\n\n\x06IDLE_B\x10\t\x12\x0c\n\x08GREETING\x10\n\x12\x0e\n\nGREETING_B\x10\x0b\x12\x0f\n\x0bREACT_ANGRY\x10\x0c\x12\x15\n\x11REACT_CELEBRATION\x10\r\x12\x0f\n\x0bREACT_HAPPY\x10\x0e\x12\x0f\n\x0bREACT_LAUGH\x10\x0f\x12\r\n\tREACT_SAD\x10\x10\x12\x10\n\x0cREACT_SCARED\x10\x11\x12\x13\n\x0fREACT_SURPRISED\x10\x12\"\x9f\x01\n\tCharacter\x12\x13\n\x0f\x43HARACTER_UNSET\x10\x00\x12\x14\n\x10PROFESSOR_WILLOW\x10\x01\x12\x13\n\x0fSPECIAL_GUEST_1\x10\x02\x12\x13\n\x0fSPECIAL_GUEST_2\x10\x03\x12\x13\n\x0fSPECIAL_GUEST_3\x10\x04\x12\x13\n\x0fSPECIAL_GUEST_4\x10\x05\x12\x13\n\x0fSPECIAL_GUEST_5\x10\x06\x62\x06proto3')
)



_QUESTDIALOG_CHARACTEREXPRESSION = _descriptor.EnumDescriptor(
  name='CharacterExpression',
  full_name='pogoprotos.data.quests.QuestDialog.CharacterExpression',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXPRESSION_UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HAPPY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYMPATHETIC', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENERGETIC', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUSHY', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMPATIENT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADMIRATION', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAD', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IDLE_B', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREETING', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREETING_B', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REACT_ANGRY', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REACT_CELEBRATION', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REACT_HAPPY', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REACT_LAUGH', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REACT_SAD', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REACT_SCARED', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REACT_SURPRISED', index=18, number=18,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=343,
  serialized_end=660,
)
_sym_db.RegisterEnumDescriptor(_QUESTDIALOG_CHARACTEREXPRESSION)

_QUESTDIALOG_CHARACTER = _descriptor.EnumDescriptor(
  name='Character',
  full_name='pogoprotos.data.quests.QuestDialog.Character',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHARACTER_UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROFESSOR_WILLOW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIAL_GUEST_1', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIAL_GUEST_2', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIAL_GUEST_3', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIAL_GUEST_4', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIAL_GUEST_5', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=663,
  serialized_end=822,
)
_sym_db.RegisterEnumDescriptor(_QUESTDIALOG_CHARACTER)


_QUESTDIALOG = _descriptor.Descriptor(
  name='QuestDialog',
  full_name='pogoprotos.data.quests.QuestDialog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='pogoprotos.data.quests.QuestDialog.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expression', full_name='pogoprotos.data.quests.QuestDialog.expression', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_uri', full_name='pogoprotos.data.quests.QuestDialog.image_uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='character', full_name='pogoprotos.data.quests.QuestDialog.character', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='character_offset', full_name='pogoprotos.data.quests.QuestDialog.character_offset', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_background_color', full_name='pogoprotos.data.quests.QuestDialog.text_background_color', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='character_tint', full_name='pogoprotos.data.quests.QuestDialog.character_tint', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUESTDIALOG_CHARACTEREXPRESSION,
    _QUESTDIALOG_CHARACTER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=822,
)

_QUESTDIALOG.fields_by_name['expression'].enum_type = _QUESTDIALOG_CHARACTEREXPRESSION
_QUESTDIALOG.fields_by_name['character'].enum_type = _QUESTDIALOG_CHARACTER
_QUESTDIALOG_CHARACTEREXPRESSION.containing_type = _QUESTDIALOG
_QUESTDIALOG_CHARACTER.containing_type = _QUESTDIALOG
DESCRIPTOR.message_types_by_name['QuestDialog'] = _QUESTDIALOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuestDialog = _reflection.GeneratedProtocolMessageType('QuestDialog', (_message.Message,), dict(
  DESCRIPTOR = _QUESTDIALOG,
  __module__ = 'pogoprotos.data.quests.quest_dialog_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.quests.QuestDialog)
  ))
_sym_db.RegisterMessage(QuestDialog)


# @@protoc_insertion_point(module_scope)
