# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/game/gamepushnotification/game_push_notification_action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/game/gamepushnotification/game_push_notification_action.proto',
  package='pogoprotos.networking.requests.game.gamepushnotification',
  syntax='proto3',
  serialized_pb=_b('\n\\pogoprotos/networking/requests/game/gamepushnotification/game_push_notification_action.proto\x12\x38pogoprotos.networking.requests.game.gamepushnotification*\xb7\x01\n\x1aGamePushNotificationAction\x12)\n%UNKNOWN_GAME_PUSH_NOTIFICATION_ACTION\x10\x00\x12 \n\x1aREGISTER_PUSH_NOTIFICATION\x10\x80\xc4\x13\x12\"\n\x1cUNREGISTER_PUSH_NOTIFICATION\x10\x81\xc4\x13\x12(\n\"OPT_OUT_PUSH_NOTIFICATION_CATEGORY\x10\x82\xc4\x13\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_GAMEPUSHNOTIFICATIONACTION = _descriptor.EnumDescriptor(
  name='GamePushNotificationAction',
  full_name='pogoprotos.networking.requests.game.gamepushnotification.GamePushNotificationAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_GAME_PUSH_NOTIFICATION_ACTION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER_PUSH_NOTIFICATION', index=1, number=320000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNREGISTER_PUSH_NOTIFICATION', index=2, number=320001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPT_OUT_PUSH_NOTIFICATION_CATEGORY', index=3, number=320002,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=155,
  serialized_end=338,
)
_sym_db.RegisterEnumDescriptor(_GAMEPUSHNOTIFICATIONACTION)

GamePushNotificationAction = enum_type_wrapper.EnumTypeWrapper(_GAMEPUSHNOTIFICATIONACTION)
UNKNOWN_GAME_PUSH_NOTIFICATION_ACTION = 0
REGISTER_PUSH_NOTIFICATION = 320000
UNREGISTER_PUSH_NOTIFICATION = 320001
OPT_OUT_PUSH_NOTIFICATION_CATEGORY = 320002


DESCRIPTOR.enum_types_by_name['GamePushNotificationAction'] = _GAMEPUSHNOTIFICATIONACTION


# @@protoc_insertion_point(module_scope)
