# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/game/gametelemetry/game_telemetry_action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/game/gametelemetry/game_telemetry_action.proto',
  package='pogoprotos.networking.requests.game.gametelemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nMpogoprotos/networking/requests/game/gametelemetry/game_telemetry_action.proto\x12\x31pogoprotos.networking.requests.game.gametelemetry*}\n\x13GameTelemetryAction\x12!\n\x1dUNKNOWN_GAME_TELEMETRY_ACTION\x10\x00\x12\x1e\n\x18\x43OLLECT_CLIENT_TELEMETRY\x10\xd0\x9d%\x12#\n\x1dGET_CLIENT_TELEMETRY_SETTINGS\x10\xd1\x9d%b\x06proto3')
)

_GAMETELEMETRYACTION = _descriptor.EnumDescriptor(
  name='GameTelemetryAction',
  full_name='pogoprotos.networking.requests.game.gametelemetry.GameTelemetryAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_GAME_TELEMETRY_ACTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLLECT_CLIENT_TELEMETRY', index=1, number=610000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_CLIENT_TELEMETRY_SETTINGS', index=2, number=610001,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=132,
  serialized_end=257,
)
_sym_db.RegisterEnumDescriptor(_GAMETELEMETRYACTION)

GameTelemetryAction = enum_type_wrapper.EnumTypeWrapper(_GAMETELEMETRYACTION)
UNKNOWN_GAME_TELEMETRY_ACTION = 0
COLLECT_CLIENT_TELEMETRY = 610000
GET_CLIENT_TELEMETRY_SETTINGS = 610001


DESCRIPTOR.enum_types_by_name['GameTelemetryAction'] = _GAMETELEMETRYACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
