# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/game/gamepoi/responses/submit_sponsor_poi_location_update_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/game/gamepoi/responses/submit_sponsor_poi_location_update_response.proto',
  package='pogoprotos.networking.responses.game.gamepoi.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nhpogoprotos/networking/responses/game/gamepoi/responses/submit_sponsor_poi_location_update_response.proto\x12\x36pogoprotos.networking.responses.game.gamepoi.responses\"(\n&SubmitSponsorPoiLocationUpdateResponseb\x06proto3')
)




_SUBMITSPONSORPOILOCATIONUPDATERESPONSE = _descriptor.Descriptor(
  name='SubmitSponsorPoiLocationUpdateResponse',
  full_name='pogoprotos.networking.responses.game.gamepoi.responses.SubmitSponsorPoiLocationUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=204,
)

DESCRIPTOR.message_types_by_name['SubmitSponsorPoiLocationUpdateResponse'] = _SUBMITSPONSORPOILOCATIONUPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitSponsorPoiLocationUpdateResponse = _reflection.GeneratedProtocolMessageType('SubmitSponsorPoiLocationUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITSPONSORPOILOCATIONUPDATERESPONSE,
  __module__ = 'pogoprotos.networking.responses.game.gamepoi.responses.submit_sponsor_poi_location_update_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.game.gamepoi.responses.SubmitSponsorPoiLocationUpdateResponse)
  ))
_sym_db.RegisterMessage(SubmitSponsorPoiLocationUpdateResponse)


# @@protoc_insertion_point(module_scope)
