# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/player/player_summary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/player/player_summary.proto',
  package='pogoprotos.data.player',
  syntax='proto3',
  serialized_pb=_b('\n+pogoprotos/data/player/player_summary.proto\x12\x16pogoprotos.data.player\"\x8e\x01\n\rPlayerSummary\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x10\n\x08\x63odename\x18\x02 \x01(\t\x12\x13\n\x0bpublic_data\x18\x03 \x01(\x0c\x12\x0c\n\x04team\x18\x04 \x01(\t\x12\x12\n\nfb_user_id\x18\x05 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\x05\x12\x12\n\nexperience\x18\x07 \x01(\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYERSUMMARY = _descriptor.Descriptor(
  name='PlayerSummary',
  full_name='pogoprotos.data.player.PlayerSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='pogoprotos.data.player.PlayerSummary.player_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='codename', full_name='pogoprotos.data.player.PlayerSummary.codename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_data', full_name='pogoprotos.data.player.PlayerSummary.public_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='team', full_name='pogoprotos.data.player.PlayerSummary.team', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fb_user_id', full_name='pogoprotos.data.player.PlayerSummary.fb_user_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='pogoprotos.data.player.PlayerSummary.level', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experience', full_name='pogoprotos.data.player.PlayerSummary.experience', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=214,
)

DESCRIPTOR.message_types_by_name['PlayerSummary'] = _PLAYERSUMMARY

PlayerSummary = _reflection.GeneratedProtocolMessageType('PlayerSummary', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERSUMMARY,
  __module__ = 'pogoprotos.data.player.player_summary_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.player.PlayerSummary)
  ))
_sym_db.RegisterMessage(PlayerSummary)


# @@protoc_insertion_point(module_scope)
